version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/SDS
hooks:
  BeforeInstall:
    - location: scripts_sds/install_dependencies
      timeout: 301
      runas: root
  AfterInstall:
    - location: scripts_sds/start_server
      timeout: 301
      runas: ec2-user
  ApplicationStop:
    - location: scripts_sds/stop_server
      timeout: 301
      runas: root


